# Generated by Django 4.2 on 2023-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210315_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]